//! TypeScript `code`-mode generation: frozen IR -> `.ts` source.
//!
//! Per schema file:
//! - `struct`   -> `export interface`
//! - `error`    -> `export interface` (the wire payload) + `export class
//!   <Name>Error` (the throwable, carrying `.data` and a static `.ordinal`)
//! - `enum`     -> `export enum` with string values (JSON interop)
//! - `protocol` -> the full RPC shape against `@comline/runtime`: an `IR_HASH`
//!   const, a `<Proto><Fn>Params` interface per function, a `<Proto>` provider
//!   interface of `Promise`-returning methods, a `<PROTO>_CALLS` table, a
//!   `<Proto>Dispatcher` (`implements Dispatch`), a `<Proto>Client`, and a
//!   `serve<Proto>` helper. Framing follows `@framing` / the package default.
//!
//! `lib` mode (an npm package) is not built yet. See design/generation.md.

use std::collections::HashMap;
use std::path::PathBuf;

use comline_core::schema::ir::compiler::interpreted::kind_search::KindValue;
use comline_core::schema::ir::frozen::schema_ir_hash;
use comline_core::schema::ir::frozen::unit::FrozenUnit;

use eyre::{bail, Result};

use comline_codegen::{GenRequest, GeneratedFile, Mode};

pub fn generate_typescript(req: &GenRequest) -> Result<Vec<GeneratedFile>> {
    if req.mode == Mode::Lib {
        bail!("typescript lib mode is not implemented yet (de-rot G2)");
    }

    let default_framing = req.default_framing.as_deref();
    Ok(req
        .schemas
        .iter()
        .map(|(namespace, units)| GeneratedFile {
            path: PathBuf::from(format!("{namespace}.ts")),
            contents: schema_source(units, default_framing),
        })
        .collect())
}

fn schema_source(units: &[FrozenUnit], default_framing: Option<&str>) -> String {
    let has_protocol = units
        .iter()
        .any(|u| matches!(u, FrozenUnit::Protocol { .. }));
    let errors = error_type_names(units);

    // Which framings the protocols in this file reach for.
    let picks: Vec<FramingChoice> = units
        .iter()
        .filter_map(|u| match u {
            FrozenUnit::Protocol { parameters, .. } => {
                Some(framing_choice(parameters, default_framing))
            }
            _ => None,
        })
        .collect();

    let mut output = String::new();
    output.push_str("// Generated by Comline\n\n");

    if has_protocol {
        let mut values = vec![
            "Client",
            "Server",
            "Handshake",
            "RuntimeError",
            "resolveKind",
        ];
        if picks.iter().any(|p| !p.jsonrpc) {
            values.push("DatagramFraming");
        }
        if picks.iter().any(|p| p.jsonrpc) {
            values.push("JsonRpcFraming");
        }
        output.push_str("import {\n");
        for v in values {
            output.push_str(&format!("    {v},\n"));
        }
        for t in [
            "Codec", "Dispatch", "Framing", "Kind", "Reply", "Transport",
        ] {
            output.push_str(&format!("    type {t},\n"));
        }
        output.push_str("} from \"@comline/runtime\";\n\n");

        output.push_str(&format!(
            "/** Canonical digest of the frozen IR this file was generated from — the\n\
             *  two ends of a connection must agree on it. */\n\
             export const IR_HASH = {:#018x}n;\n\n",
            schema_ir_hash(units)
        ));
    }

    for unit in units {
        match unit {
            FrozenUnit::Struct { name, fields, .. } => {
                output.push_str(&interface(name, fields));
            }
            FrozenUnit::Error {
                name,
                fields,
                ordinal,
                ..
            } => {
                output.push_str(&interface(name, fields));
                output.push_str(&error_class(name, *ordinal));
            }
            FrozenUnit::Enum { name, variants, .. } => {
                output.push_str(&string_enum(name, variants));
            }
            FrozenUnit::Protocol {
                name,
                functions,
                parameters,
                ..
            } => {
                output.push_str(&protocol(
                    name,
                    functions,
                    &framing_choice(parameters, default_framing),
                    &errors,
                ));
            }
            _ => {}
        }
    }

    output
}

/// Schema-global error ordinal -> the `error` interface's name.
fn error_type_names(units: &[FrozenUnit]) -> HashMap<u16, String> {
    units
        .iter()
        .filter_map(|u| match u {
            FrozenUnit::Error { ordinal, name, .. } => Some((*ordinal, name.clone())),
            _ => None,
        })
        .collect()
}

// ── data types ─────────────────────────────────────────────────────────────

fn interface(name: &str, fields: &[FrozenUnit]) -> String {
    let mut s = format!("export interface {name} {{\n");
    for field in fields {
        if let FrozenUnit::Field {
            name,
            kind_value,
            optional,
            ..
        } = field
        {
            let opt = if *optional { "?" } else { "" };
            s.push_str(&format!("    {name}{opt}: {};\n", ts_type(kind_value)));
        }
    }
    s.push_str("}\n\n");
    s
}

/// The throwable for an `error`: a provider `throw`s `new <Name>Error(data)`;
/// the dispatcher catches it and the client re-raises it, both keyed by
/// `<Name>Error.ordinal`.
fn error_class(name: &str, ordinal: u16) -> String {
    format!(
        "export class {name}Error extends Error {{\n\
        \x20   static readonly ordinal = {ordinal};\n\
        \x20   constructor(readonly data: {name}) {{\n\
        \x20       super(\"{name}\");\n\
        \x20       this.name = \"{name}Error\";\n\
        \x20   }}\n\
        }}\n\n"
    )
}

fn string_enum(name: &str, variants: &[FrozenUnit]) -> String {
    let mut s = format!("export enum {name} {{\n");
    for variant in variants {
        if let FrozenUnit::EnumVariant(kv, _) = variant {
            let v = match kv {
                KindValue::EnumVariant(n, _) | KindValue::Namespaced(n, _) => n.clone(),
                _ => "Unknown".to_string(),
            };
            s.push_str(&format!("    {v} = \"{v}\",\n"));
        }
    }
    s.push_str("}\n\n");
    s
}

// ── framing selection ──────────────────────────────────────────────────────

struct FramingChoice {
    /// The runtime class name — `DatagramFraming` or `JsonRpcFraming`.
    ctor: &'static str,
    jsonrpc: bool,
}

fn framing_for(name: &str) -> Option<FramingChoice> {
    match name {
        "jsonrpc" | "json-rpc" | "jsonrpc-2.0" => Some(FramingChoice {
            ctor: "JsonRpcFraming",
            jsonrpc: true,
        }),
        "datagram" | "comline.datagram" => Some(FramingChoice {
            ctor: "DatagramFraming",
            jsonrpc: false,
        }),
        _ => None,
    }
}

/// A protocol's framing, most specific first: its own `@framing`, then the
/// package `default_framing`, then datagram.
fn framing_choice(parameters: &[FrozenUnit], default_framing: Option<&str>) -> FramingChoice {
    annotation(parameters, "framing")
        .and_then(framing_for)
        .or_else(|| default_framing.and_then(framing_for))
        .unwrap_or(FramingChoice {
            ctor: "DatagramFraming",
            jsonrpc: false,
        })
}

/// The value of a scalar `@key = value` annotation (a `FrozenUnit::Property`).
fn annotation<'a>(parameters: &'a [FrozenUnit], key: &str) -> Option<&'a str> {
    parameters.iter().find_map(|p| match p {
        FrozenUnit::Property { name, expression } if name == key => expression.as_deref(),
        _ => None,
    })
}

// ── protocol ───────────────────────────────────────────────────────────────

struct FnInfo {
    name: String,
    params_ty: Option<String>,
    args: Vec<(String, String)>,
    /// The declared return type; `void` for a one-way call or a `()` return.
    ret: String,
    one_way: bool,
    /// `(ordinal, error interface name)` for each `!`. Empty for a one-way call.
    throws: Vec<(u16, String)>,
}

fn protocol(
    proto: &str,
    functions: &[FrozenUnit],
    framing: &FramingChoice,
    errors: &HashMap<u16, String>,
) -> String {
    let fns: Vec<FnInfo> = functions
        .iter()
        .filter_map(|f| match f {
            FrozenUnit::Function {
                name,
                arguments,
                _return,
                throws,
                ..
            } => {
                let one_way = _return.is_none();
                let args: Vec<(String, String)> = arguments
                    .iter()
                    .map(|a| (a.name.clone(), ts_type(&a.kind)))
                    .collect();
                let params_ty = (!args.is_empty()).then(|| format!("{proto}{}Params", pascal(name)));
                let ret = match _return {
                    None | Some(KindValue::Unit) => "void".to_string(),
                    Some(kv) => ts_type(kv),
                };
                let throws: Vec<(u16, String)> = if one_way {
                    Vec::new()
                } else {
                    throws
                        .iter()
                        .map(|o| {
                            (
                                *o,
                                errors
                                    .get(o)
                                    .cloned()
                                    .unwrap_or_else(|| format!("UnknownError{o}")),
                            )
                        })
                        .collect()
                };
                Some(FnInfo {
                    name: name.clone(),
                    params_ty,
                    args,
                    ret,
                    one_way,
                    throws,
                })
            }
            _ => None,
        })
        .collect();

    let mut s = String::new();

    // 1. a params interface per function that takes arguments
    for f in &fns {
        if let Some(ty) = &f.params_ty {
            s.push_str(&format!("export interface {ty} {{\n"));
            for (name, tsty) in &f.args {
                s.push_str(&format!("    {name}: {tsty};\n"));
            }
            s.push_str("}\n\n");
        }
    }

    if fns.is_empty() {
        s.push_str(&format!("export interface {proto} {{}}\n\n"));
        return s;
    }

    // 2. the provider interface — every call is async
    s.push_str(&format!("export interface {proto} {{\n"));
    for f in &fns {
        if !f.throws.is_empty() {
            let names = f
                .throws
                .iter()
                .map(|(_, n)| format!("{n}Error"))
                .collect::<Vec<_>>()
                .join(" | ");
            s.push_str(&format!("    /** @throws {{{names}}} */\n"));
        }
        s.push_str(&format!(
            "    {}({}): Promise<{}>;\n",
            f.name,
            f.params_ty.as_ref().map_or(String::new(), |t| format!("params: {t}")),
            f.ret
        ));
    }
    s.push_str("}\n\n");

    // 3. the call table
    let calls_const = format!("{}_CALLS", screaming_snake(proto));
    let call_names = fns
        .iter()
        .map(|f| format!("\"{}\"", f.name))
        .collect::<Vec<_>>()
        .join(", ");
    s.push_str(&format!(
        "export const {calls_const} = [{call_names}] as const;\n\n"
    ));

    // 4. the dispatcher
    s.push_str(&format!(
        "export class {proto}Dispatcher implements Dispatch {{\n\
        \x20   constructor(private readonly impl: {proto}) {{}}\n\n\
        \x20   calls(): readonly string[] {{\n\
        \x20       return {calls_const};\n\
        \x20   }}\n\n\
        \x20   async dispatch(call: Kind, params: Uint8Array, codec: Codec, reply: Reply): Promise<void> {{\n\
        \x20       switch (resolveKind(call, {calls_const})) {{\n"
    ));
    for (i, f) in fns.iter().enumerate() {
        s.push_str(&format!("            case {i}: {{\n"));
        let call_arg = match &f.params_ty {
            Some(ty) => {
                s.push_str(&format!(
                    "                const p = codec.decode<{ty}>(params);\n"
                ));
                "p"
            }
            None => "",
        };
        if f.one_way {
            s.push_str(&format!(
                "                await this.impl.{}({call_arg});\n\
                 \x20               return;\n",
                f.name
            ));
        } else if f.throws.is_empty() {
            s.push_str(&format!(
                "                reply.ok(codec.encode((await this.impl.{}({call_arg})) ?? null));\n\
                 \x20               return;\n",
                f.name
            ));
        } else {
            s.push_str("                try {\n");
            s.push_str(&format!(
                "                    reply.ok(codec.encode((await this.impl.{}({call_arg})) ?? null));\n",
                f.name
            ));
            s.push_str("                } catch (e) {\n");
            for (_, err) in &f.throws {
                s.push_str(&format!(
                    "                    if (e instanceof {err}Error) {{ reply.err({err}Error.ordinal, codec.encode(e.data)); return; }}\n"
                ));
            }
            s.push_str("                    throw e;\n");
            s.push_str("                }\n");
            s.push_str("                return;\n");
        }
        s.push_str("            }\n");
    }
    s.push_str(
        "            default:\n\
        \x20               throw RuntimeError.unknownCall();\n\
        \x20       }\n\
        \x20   }\n\
        }\n\n",
    );

    // 5. the client
    s.push_str(&format!(
        "export class {proto}Client {{\n\
        \x20   constructor(private readonly client: Client) {{}}\n\n\
        \x20   static async connect(transport: Transport, codec: Codec, framing: Framing = new {ctor}()): Promise<{proto}Client> {{\n\
        \x20       const hs = new Handshake({{ irHash: IR_HASH, wireFormat: codec.name, framing: framing.name }});\n\
        \x20       return new {proto}Client(await Client.connect(transport, codec, hs, framing));\n\
        \x20   }}\n",
        ctor = framing.ctor
    ));
    for (i, f) in fns.iter().enumerate() {
        let sig_params = f
            .params_ty
            .as_ref()
            .map_or(String::new(), |t| format!("params: {t}"));
        let arg = if f.params_ty.is_some() { "params" } else { "null" };
        s.push('\n');
        if f.one_way {
            s.push_str(&format!(
                "    async {}({sig_params}): Promise<void> {{\n\
                 \x20       await this.client.notify({{ id: {i}, name: \"{}\" }}, {arg});\n\
                 \x20   }}\n",
                f.name, f.name
            ));
            continue;
        }
        s.push_str(&format!(
            "    async {}({sig_params}): Promise<{}> {{\n\
             \x20       const env = await this.client.call({{ id: {i}, name: \"{}\" }}, {arg});\n",
            f.name, f.ret, f.name
        ));
        if f.ret == "void" {
            s.push_str("        if (\"ok\" in env) return;\n");
        } else {
            s.push_str(&format!(
                "        if (\"ok\" in env) return this.client.codec.decode<{}>(env.ok);\n",
                f.ret
            ));
        }
        if f.throws.is_empty() {
            s.push_str("        throw RuntimeError.remote(env.err.id);\n");
        } else {
            s.push_str("        switch (env.err.id) {\n");
            for (_, err) in &f.throws {
                s.push_str(&format!(
                    "            case {err}Error.ordinal:\n\
                     \x20               throw new {err}Error(this.client.codec.decode<{err}>(env.err.body));\n"
                ));
            }
            s.push_str("            default:\n");
            s.push_str("                throw RuntimeError.remote(env.err.id);\n");
            s.push_str("        }\n");
        }
        s.push_str("    }\n");
    }
    s.push_str("}\n\n");

    // 6. the serve helper
    s.push_str(&format!(
        "export function serve{proto}(impl: {proto}, transport: Transport, codec: Codec, framing: Framing = new {ctor}()): Promise<void> {{\n\
        \x20   const hs = new Handshake({{ irHash: IR_HASH, wireFormat: codec.name, framing: framing.name }});\n\
        \x20   return new Server(new {proto}Dispatcher(impl), codec, framing).serveHandshaked(transport, hs);\n\
        }}\n\n",
        ctor = framing.ctor
    ));

    s
}

// ── type mapping ───────────────────────────────────────────────────────────

fn ts_type(kind: &KindValue) -> String {
    match kind {
        KindValue::Primitive(p) => map_str_type(p.name()),
        KindValue::Namespaced(name, _) => map_str_type(name),
        KindValue::EnumVariant(name, _) => name.clone(),
        KindValue::Unit => "void".to_string(),
        _ => "unknown".to_string(),
    }
}

fn map_str_type(s: &str) -> String {
    if let Some(inner) = s.strip_suffix("[]") {
        return format!("{}[]", map_str_type(inner));
    }
    match s {
        "string" | "str" => "string".to_string(),
        "bool" => "boolean".to_string(),
        // 128-bit integers overflow `number`'s 2^53 exact range — use `bigint`.
        "u128" | "i128" | "s128" => "bigint".to_string(),
        // TypeScript has one plain numeric type; the narrower widths map to it.
        "float" | "double" | "int" | "u8" | "u16" | "u32" | "u64" | "i8" | "i16" | "i32" | "i64"
        | "s8" | "s16" | "s32" | "s64" => "number".to_string(),
        // A named type from the schema (another struct / enum) — pass through.
        other => other.to_string(),
    }
}

/// `get_user` -> `GetUser`, for deriving a type name from a function name.
fn pascal(s: &str) -> String {
    s.split('_')
        .filter(|w| !w.is_empty())
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                Some(first) => first.to_uppercase().collect::<String>() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

/// `UserService` -> `USER_SERVICE`, for the call-table const.
fn screaming_snake(s: &str) -> String {
    let mut out = String::new();
    for (i, ch) in s.char_indices() {
        if ch.is_uppercase() && i != 0 {
            out.push('_');
        }
        out.extend(ch.to_uppercase());
    }
    out
}
